INSERT INTO users(name, email, password, profile, enabled) VALUES('Administrador', 'admin@vertzon.com.br', '$2y$12$6OMXZ8bPPgT1iEYf2NrxuO7O1tU/gASkecf9SS2lCGUuU1O2QHb7G', 'ADMINISTRATOR', 1)
INSERT INTO users(name, email, password, profile, enabled) VALUES('Webmaster', 'webmaster@vertzon.com.br', '$2y$12$6OMXZ8bPPgT1iEYf2NrxuO7O1tU/gASkecf9SS2lCGUuU1O2QHb7G', 'WEBMASTER', 1)

INSERT INTO legal_bases(name, description) VALUES('I - Consentimento do Titular', 'Mediante o fornecimento de consentimento pelo titular');
INSERT INTO legal_bases(name, description) VALUES('II - Obrigação Legal','Para o cumprimento de obrigação legal ou regulatória pelo controlador');
INSERT INTO legal_bases(name, description) VALUES('III - Administração Pública', 'Pela administração pública, para o tratamento e uso compartilhado de dados necessários à execução de políticas públicas previstas em leis e regulamentos ou respaldadas em contratos, convênios ou instrumentos congêneres, observadas as disposições do capítulo IV desta Lei')
INSERT INTO legal_bases(name, description) VALUES('IV - Pesquisas e Estudos', 'Para a realização de estudos por órgão de pesquisa, garantida, sempre que possível, anonimização dos dados pessoais')
INSERT INTO legal_bases(name, description) VALUES('V - Procedimentos Contratuais', 'Quando necessário para a execução de contrato ou de procedimentos preliminares a contrato do qual seja parte o titular, a pedido do titular dos dados')
INSERT INTO legal_bases(name, description) VALUES('VI - Procedimentos Jurídicos', 'Para o exercício regular de direitos em processo judicial, administrativo ou arbitral, esse último nos termos da Lei nº 9.307, de 23 de setembro de 1996 (Lei de Arbitragem)')
INSERT INTO legal_bases(name, description) VALUES('VII - Proteção à vida', 'Para a proteção da vida ou da incolumidade física do titular ou de terceiros')
INSERT INTO legal_bases(name, description) VALUES('VIII - Tutela da Saúde', 'Para a tutela da saúde, exclusivamente, em procedimento realizado por profissionais de saúde, serviços de saúde ou autoridade sanitária')
INSERT INTO legal_bases(name, description) VALUES('IX - Interesses Legítimos', 'Quando necessário para atender aos interesses legítimos do controlador ou de terceiro, exceto no caso de prevalecerem direitos ou liberdades fundamentais do titular que exijam a proteção dos dados pessoais')
INSERT INTO legal_bases(name, description) VALUES('X - Proteção de Crédito', 'Para a proteção do crédito, inclusive quando ao disposto na legislação pertinente')

INSERT INTO finalities(name, description) VALUES('Marketing e Propaganda', 'Para fins de marketing e propaganda direcionados por meios eletrônicos ou não')

INSERT INTO legal_base_finalities(id_legal_base, id_finality) VALUES(1, 1)

INSERT INTO personal_data_types(name, description, method, category) VALUES('NOME', 'Nome pessoal, completo ou parcial', '2', '0')
INSERT INTO personal_data_types(name, description, method, category) VALUES('RG', 'Certidão de Registro Geral', '0', '0')
INSERT INTO personal_data_types(name, description, method, category) VALUES('CPF', 'Cadastro de Pessoa Física', '1', '0')
INSERT INTO personal_data_types(name, description, method, category) VALUES('CDI', 'Número de Certificado de Dispensa de Incorporação das Forças Armadas Brasileiras', '0', '0')
INSERT INTO personal_data_types(name, description, method, category) VALUES('CNH', 'Carteira Nacional de Habilitação', '0', '0')
INSERT INTO personal_data_types(name, description, method, category) VALUES('PASSAPORTE', 'Número de Passaporte', '0', '0')
INSERT INTO personal_data_types(name, description, method, category) VALUES('TÍTULO DE ELEITOR', 'Número de Título de Eleitor', '0', '0')
INSERT INTO personal_data_types(name, description, method, category) VALUES('ENDEREÇO', 'Endereços residenciais ou comerciais', '2', '0')
INSERT INTO personal_data_types(name, description, method, category) VALUES('TELEFONE', 'Número de telefone fixo ou móvel', '0', '0')
INSERT INTO personal_data_types(name, description, method, category) VALUES('EMAIL', 'Endereço de e-mail', '0', '0')

INSERT INTO identification_fields(name, id_personal_data_type) VALUES('NOME', 1)
INSERT INTO identification_fields(name, id_personal_data_type) VALUES('RG', 2)
INSERT INTO identification_fields(name, id_personal_data_type) VALUES('CPF', 3)
INSERT INTO identification_fields(name, id_personal_data_type) VALUES('CDI', 4)
INSERT INTO identification_fields(name, id_personal_data_type) VALUES('CNH', 5)
INSERT INTO identification_fields(name, id_personal_data_type) VALUES('PASSAPORTE', 6)
INSERT INTO identification_fields(name, id_personal_data_type) VALUES('TÍTULO DE ELEITOR', 7)
INSERT INTO identification_fields(name, id_personal_data_type) VALUES('ENDEREÇO', 8)
INSERT INTO identification_fields(name, id_personal_data_type) VALUES('TELEFONE', 9)
INSERT INTO identification_fields(name, id_personal_data_type) VALUES('EMAIL', 10)

INSERT INTO identification_columns(column_name, id_identification_field) VALUES('nome', 1)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('nome_completo', 1)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('nome_pessoal', 1)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('sobrenome', 1)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('nome_do_meio', 1)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('ultimo_nome', 1)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('nome_final', 1)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('name', 1)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('first_name', 1)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('last_name', 1)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('rg', 2)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('registro_geral', 2)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('reg_geral', 2)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('r_g', 2)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('registrogeral', 2)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('identificacao', 2)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('cpf', 3)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('cadastro_pessoa_fisica', 3)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('pessoa_fisica', 3)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('cadastro_pessoafisica', 3)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('cadastropessoa_fisica', 3)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('cad_pessoa_fisica', 3)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('cdi', 4)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('csm', 4)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('certificado_dispensa', 4)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('dispensa', 4)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('certificado_dispensa_incorporacao', 4)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('certificado_de_dispensa_de_incorporacao', 4)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('cert_dispensa_incorporacao', 4)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('cnh', 5)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('carteira_habilitacao', 5)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('carteira_de_habilitacao', 5)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('habilitacao', 5)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('carteira_habilitacao_nacional', 5)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('carteira_motorista', 5)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('carteira_de_motorista', 5)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('passaporte', 6)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('passport', 6)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('titulo_eleitor', 7)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('titulo', 7)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('titulo_de_eleitor', 7)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('eleitor', 7)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('carteira_eleitor', 7)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('carteira_de_eleitor', 7)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('endereco', 8)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('end', 8)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('end_residencial', 8)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('endereco_residencial', 8)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('end_comercial', 8)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('endereco_comercial', 8)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('logradouro', 8)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('bairro', 8)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('rua', 8)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('telefone', 9)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('tel', 9)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('fone', 9)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('numero_telefone', 9)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('contato', 9)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('numero_movel', 9)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('numero_celular', 9)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('fixo', 9)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('telefone_fixo', 9)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('email', 10)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('e-mail', 10)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('e_mail', 10)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('endereco_email', 10)
INSERT INTO identification_columns(column_name, id_identification_field) VALUES('endereco_de_email', 10)

INSERT INTO learning_regexes(name, description, pattern, id_personal_data_type) VALUES ('RG', 'Express�o Regular para identificação de RG', '(^\d{1,2}).?(\d{3}).?(\d{3})-?(\d{1}|X|x$)', 2)
INSERT INTO learning_regexes(name, description, pattern, id_personal_data_type) VALUES ('TELEFONE', 'Express�o Regular para identificação de TELEFONE', '(\(?\d{2}\)?\s)?(\d{4,5}\-\d{4})', 9)
INSERT INTO learning_regexes(name, description, pattern, id_personal_data_type) VALUES ('EMAIL', 'Express�o Regular para identificação de EMAIL', '(?:[a-z0-9!#$%&''*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&''*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])', 10)

INSERT INTO learning_scripts(name, description, code, id_personal_data_type) VALUES ('CPF', 'Script para valida��o de CPFs', 'function evalScript(value) {    value.trim();   value.replace(''.'','''');   value.replace(''-'','''');    var soma = 0;   var resto = 0;   if (value == "00000000000") return false;     for (i=1; i<=9; i++) {      soma = soma + parseInt(value.substring(i-1, i)) * (11 - i);   }    resto = (soma * 10) % 11;     if ((resto == 10) || (resto == 11)) {      resto = 0;   }    if (resto != parseInt(value.substring(9, 10))) {      return false;   }    soma = 0;    for (i = 1; i <= 10; i++) {      soma = soma + parseInt(value.substring(i-1, i)) * (12 - i);   }   resto = (soma * 10) % 11;    if ((resto == 10) || (resto == 11)) {      resto = 0;   }    if (resto != parseInt(value.substring(10, 11))) {      return false;    }   return true;  }', 3)

INSERT INTO database_types(name, description, driver, prefix) VALUES ('Driver para MySQL > 5.7', 'Conexão com bases de dados MySQL versão maior que 5.7', 'com.mysql.cj.jdbc.Driver', 'jdbc:mysql://')
INSERT INTO database_types(name, description, driver, prefix) VALUES ('Driver para Microsoft SQL Server', 'Conexão com bases de dados Microsoft SQL Server', 'com.microsoft.sqlserver.jdbc.SQLServerDriver', 'jdbc:sqlserver://')
INSERT INTO database_types(name, description, driver, prefix) VALUES ('Driver para Oracle', 'Conexão com bases de dados Oracle', 'oracle.jdbc.driver.OracleDriver', 'jdbc:oracle:thin:@')
INSERT INTO database_types(name, description, driver, prefix) VALUES ('Driver para MongoDB', 'Conexão com bases de dados MongoDB', 'mongodb.jdbc.MongoDriver', 'mongo://')

INSERT INTO datasources(name, description, ip, port, url, username, password, id_database_type, data_learning) VALUES('discovery_db', 'Vertzon VDiscovery SQL Server', 'localhost', 1433, 'jdbc:sqlserver://localhost:1433;databaseName=discovery_db', 'sa', 'Vertzon#2018', 2, 0)
INSERT INTO datasources(name, description, ip, port, url, username, password, id_database_type, data_learning) VALUES('crm_db', 'CRM_DB', 'localhost', 3306, 'jdbc:mysql://localhost:3306/crm_db', 'root', 'Vertzon#2018', 1, 0)
INSERT INTO datasources(name, description, ip, port, url, username, password, id_database_type, data_learning) VALUES('ORCL', 'oracle', 'servicedesk.vertzon.com.br', 1521, 'jdbc:oracle:thin:@servicedesk.vertzon.com.br:1521:ORCL', 'System', 'Vtz1317@#', 3, 0)
INSERT INTO datasources(name, description, ip, port, url, username, password, id_database_type, data_learning) VALUES('gconsenti', 'mongo', 'localhost', 27017, 'mongo://localhost:27017/gconsenti', 'erick', 'Vtz1317@#', 4, 0)
INSERT INTO datasources(name, description, ip, port, url, username, password, id_database_type, data_learning) VALUES('machine_learning', 'nomes', 'localhost', 1433, 'jdbc:sqlserver://localhost:1433;databaseName=machine_learning', 'sa', 'Vertzon#2018', 2, 1)

INSERT INTO datasource_legal_base_finalities(id_datasource, id_legal_base_finality) VALUES(1, 1)
INSERT INTO datasource_legal_base_finalities(id_datasource, id_legal_base_finality) VALUES(2, 1)
INSERT INTO datasource_legal_base_finalities(id_datasource, id_legal_base_finality) VALUES(3, 1)

INSERT INTO learning_datas(name, description, id_datasource, table_name, decision_column, class_column, minimum_term_frequency, minimum_tokenizer_steps, maximum_tokenizer_steps, use_idf, use_stemmer, words_to_keep, id_personal_data_type) VALUES('machine_learning', 'Aprendizado de nomes', 5, 'persons', 'value', 'class', 1, 0, 1000, 1, 0, 10000000, 1)

INSERT INTO error_messages(label,desc_error,error_code) VALUES ('ID_NOT_FOUND', 'Aplicação de código %d não existe.', 'gc-0100')  
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('ID_IN_USE', 'Aplicação de código %d em uso.', 'gc-0101')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DIRECTORY', 'O caminho do diretório deve ser preenchido.', 'gc-0102')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_APP_PARAMETER', 'Os parâmetros do aplicativo não podem ser nulos.', 'gc-0103')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_NAME', 'O nome não pode estar vazio.', 'gc-0104')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DATABASE_TYPE_DRIVER', 'O driver não pode ser nulo.', 'gc-0105')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DATABASE_TYPE_PREFIX', 'O prefixo não pode ser nulo.', 'gc-0106')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DATABASE_TYPE', 'O tipo de fonte de dados deve ser preenchido.', 'gc-0107')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_IP', 'O IP deve ser preenchido.', 'gc-0108')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DATASOURCE_PORT', 'A porta deve ser preenchida.', 'gc-0109')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_LEGAL_BASE_FINALITIES', 'Ao menos uma finalidade por base legal deve ser selecionada.', 'gc-0110')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DATASOURCE_USERNAME', 'O usuário deve ser preenchido.', 'gc-0111')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_PASSWORD', 'A senha deve ser preenchida.', 'gc-0112')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DATASOURCE_LEGALBASE', 'Ao menos uma finalidade por base legal deve ser selecionada.', 'gc-0113')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DATASOURCE_URL', 'É necessária uma URL de conexão.', 'gc-0114')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DATASOURCE_LEARNING', 'O uso de Machine Learning deve ser informado.', 'gc-0115')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('DUPLICATED_DATASOURCE', 'Não é possível adicionar duplicatas de ''FONTE DE DADOS''.', 'gc-0116')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('DUPLICATED_FILESOURCE', 'Não é possível adicionar duplicatas de ''DIRETÓRIO DE DADOS''.', 'gc-0117')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('DUPLICATED_NAME', 'O nome atual da finalidade já foi cadastrado.', 'gc-0118')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DESCRIPTION', 'A descrição deve ser preenchida.', 'gc-0119')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('COLUMN_ID_NOT_FOUND', 'A coluna de identificação de código %d não existe.', 'gc-0120')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('PERSONAL_DATA_ID_NOT_FOUND', 'O tipo de dado pessoal de código %d não existe.', 'gc-0121')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_TABLE', 'A tabela não pode estar vazia.', 'gc-0122')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_COLUMN', 'A coluna não pode estar vazia.', 'gc-0123')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('INVALID_DATASOURCE', 'Selecione uma fonte de dados válida.', 'gc-0124')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NOT_DATA_LEARNING', 'Base de dados inapta a ser utilizada para banco de dados de aprendizado.', 'gc-0125')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('INVALID_DATATYPE', 'Selecione um tipo de dado pessoal válido.', 'gc-0126')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('DATASOURCE_ALREADY_IN_USE', 'Este banco de dados de aprendizado já está sendo utilizado por outro tipo de dados.  Não é possível duplicar verificadores; selecione outro.', 'gc-0127')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_PATTERN', 'O valor da ''EXPRESSÃO REGULAR'' não pode estar vazio.', 'gc-0128')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('DUPLICATED_REGEX', 'Já existe uma expressão regular com este padrão. Não é possível adicionar o mesmo tipo de verificação para mais de um tipo de dados. Por favor, utilize outro padrão.', 'gc-0129')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('DATATYPE_ALREADY_IN_USE', 'Este tipo de dado pessoal já está atrelado a outra validação.', 'gc-0130')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_CODE', 'O código a ser executado não pode estar vazio.', 'gc-0131')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('DUPLICATED_SCRIPT', 'Já existe um script com este código. Não é possível adicionar o mesmo tipo de verificação para mais de um tipo de dados. Por favor, utilize outro script.', 'gc-0132')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('LEGAL_BASE_ID_NOT_FOUND', 'A base legal de código %d não existe.', 'gc-0133')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('FINALITY_ID_NOT_FOUND', 'A finalidade de código %d não existe.', 'gc-0134')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DATATYPE', 'O tipo de dado pessoal deve ser preenchido.', 'gc-0135')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_IDENTIFICATION_TYPE', 'Selecione um tipo de identificação de dados.', 'gc-0136')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_DATATYPE_CATEGORY', 'Selecione uma categoria de dado pessoal.', 'gc-0137')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_START_DATE', 'É necessário especificar a data de início da varredura.', 'gc-0138')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('INVALID_START_DATE', 'A varredura deve ter um horario futuro.', 'gc-0139')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_FILESOURCE', 'É necessário especificar a fonte de dados da varredura.', 'gc-0140')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_SCAN_TYPE', 'É necessário especificar o tipo de varredura.', 'gc-0141')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('DATABASE_NOT_FOUND', 'Não existe um banco de dados com código %d.', 'gc-0142')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_EMAIL', 'O e-mail deve ser preenchido.', 'gc-0143')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('PASSWORD_LENGTH', 'A senha deve conter no mínimo 8 caracteres.', 'gc-0144')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('PASSWORD_REQUIREMENTS', 'A senha deve conter no mínimo uma letra minúscula, uma letra maiúscula e um caractere especial.', 'gc-0145')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_PROFILE', 'O perfil de acesso não pode estar nulo.', 'gc-0146')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('EMAIL_ALREADY_EXISTS', 'Este email já foi cadastrado.', 'gc-0147')
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('INVALID_ERROR_CODE', 'Código de erro inválido.', 'gc-0148')  
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_ERROR_LABEL', 'O nome do erro não pode ser nulo.', 'gc-0149')  
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_ERROR_DESC', 'A descrição do erro não pode ser nula.', 'gc-0150')  
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_LABEL_CODE', 'O código da mensagem não pode ser nulo.', 'gc-0151')  
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_LABEL_ENUM', 'O identificador de página não pode ser nulo.', 'gc-0152')  
INSERT INTO error_messages(label,desc_error,error_code) VALUES ('NULL_JSF_LABEL', 'O nome da mensagem não pode ser nulo.', 'gc-0153')  

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_REG', 'Cadastro de Configurações de Aplicativo', 'gc-label-0000')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_REG', 'CADASTRAR CONFIGURAÇÃO DE APLICATIVO', 'gc-label-0001')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_REG', 'Nome', 'gc-label-0002')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_REG', 'Descrição', 'gc-label-0003')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_REG', 'Parâmetros JVM', 'gc-label-0004')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_REG', 'Salvar', 'gc-label-0005')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_REG', 'Buscar', 'gc-label-0006')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_REG', 'Cadastro de Tipo de Fonte de Dados', 'gc-label-0007')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_REG', 'TIPO DE FONTE DE DADOS', 'gc-label-0008')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_REG', 'Nome', 'gc-label-0009')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_REG', 'Descrição', 'gc-label-0010')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_REG', 'Driver', 'gc-label-0011')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_REG', 'Prefixo', 'gc-label-0012')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_REG', 'Salvar', 'gc-label-0013')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_REG', 'Buscar', 'gc-label-0014')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Cadastro de Fonte de Dados', 'gc-label-0015')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'CADASTRAR FONTE DE DADOS', 'gc-label-0016')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Tipo de Fonte de Dados', 'gc-label-0017')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'IP', 'gc-label-0018')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Porta', 'gc-label-0019')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Nome (SID caso Oracle)', 'gc-label-0020')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Base de autenticação (caso MongoDB)', 'gc-label-0021')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Descrição', 'gc-label-0022')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Usuário', 'gc-label-0023')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Senha', 'gc-label-0024')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Finalidades por Base Legal', 'gc-label-0025')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Aprendizado: ', 'gc-label-0026')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Não', 'gc-label-0027')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Sim', 'gc-label-0028')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Salvar', 'gc-label-0029')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_REG', 'Buscar', 'gc-label-0030')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_REG', 'Cadastro de Diretórios de Arquivos', 'gc-label-0031')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_REG', 'CADASTRAR DIRETÓRIO DE ARQUIVOS', 'gc-label-0032')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_REG', 'Nome', 'gc-label-0033')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_REG', 'Descrição', 'gc-label-0034')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_REG', 'Diretório de arquivos', 'gc-label-0035')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_REG', 'Usuário', 'gc-label-0036')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_REG', 'Senha', 'gc-label-0037')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_REG', 'Finalidades por Base Legal', 'gc-label-0038')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_REG', 'Salvar', 'gc-label-0039')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_REG', 'Buscar', 'gc-label-0040')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_REG', 'Cadastro de Finalidade', 'gc-label-0041')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_REG', 'CADASTRAR FINALIDADE', 'gc-label-0042')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_REG', 'Nome', 'gc-label-0043')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_REG', 'Descrição', 'gc-label-0044')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_REG', 'Salvar', 'gc-label-0045')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_REG', 'Buscar', 'gc-label-0046')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_REG', 'Cadastro de Coluna de Identificação', 'gc-label-0047')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_REG', 'CADASTRAR COLUNA DE IDENTIFICAÇÃO', 'gc-label-0048')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_REG', 'Nome', 'gc-label-0049')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_REG', 'Salvar', 'gc-label-0050')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_REG', 'Buscar', 'gc-label-0051')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_REG', 'Cadastro de Campo de Identificação', 'gc-label-0052')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_REG', 'CADASTRAR CAMPO DE IDENTIFICAÇÃO', 'gc-label-0053')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_REG', 'Nome', 'gc-label-0054')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_REG', 'Tipo de Dado Pessoal', 'gc-label-0055')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_REG', 'Colunas de Identificação', 'gc-label-0056')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_REG', 'Salvar', 'gc-label-0057')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_REG', 'Buscar', 'gc-label-0058')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Cadastro de Data', 'gc-label-0059')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'CADASTRAR DATA', 'gc-label-0060')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Nome', 'gc-label-0061')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Descrição', 'gc-label-0062')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Fonte de dados', 'gc-label-0063')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Tabela de Decisão', 'gc-label-0064')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Coluna de Decisão', 'gc-label-0065')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Coluna de Classe', 'gc-label-0066')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Tipo de Dado Pessoal', 'gc-label-0067')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'USAR TF-IDF?', 'gc-label-0068')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'TF-IDF é um algoritmo para medição de termos com ocorrência frequente que podem ser relevantes a um tópico. É recomendado para a leitura de trechos de texto, porém pode desequilibrar um trecho de texto devido a preposições como "a", "e, "da", "de", etc.', 'gc-label-0069')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'USAR ESTEMIZAÇÃO', 'gc-label-0070')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'A Estemização é um método para reduzir palavras flexionadas ao seu tronco ou raiz. Ajuda na busca transformando palavras flexionadas em seus sinônimos simples. NÃO É RECOMENDADO PARA IDIOMAS COM GRANDE DERIVAÇÃO LINGUÍSTICA (Ex: Alemão, Português).', 'gc-label-0071')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'FREQUÊNCIA MÍNIMA DE TERMOS', 'gc-label-0072')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Só aplicável se usando TF-IDF. Remove termos que apareçam em mais de x% de documentos. Ideal para remover preposições desnecessárias que podem diminuir a precisão de um algoritmo.', 'gc-label-0073')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'NGRAMs', 'gc-label-0074')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'O Tokenizador NGram separa uma palavra por pedaços referentes à quantidade de letras específicadas. Exemplo: um número de 3-3 (mínimo/máximo) com a palavra "abelha" faria uma separação dos tokens "abe", "bel", "elh", "lha" para serem validadas.', 'gc-label-0075')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Mínimo', 'gc-label-0076')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Máximo', 'gc-label-0077')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'QUANTIDADE DE PALAVRAS MANTIDAS', 'gc-label-0078')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Mantém a quantidade especificada de palavras para predições mais rápidas e precisas em predições futuras. É recomendado manter um número alto neste item, mas não tão alto que ocupe uma quantidade grande de espaço do modelo (caso ele exista).', 'gc-label-0079')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Salvar', 'gc-label-0080')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_REG', 'Buscar', 'gc-label-0081')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_REG', 'Cadastro de Expressão Regular', 'gc-label-0082')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_REG', 'CADASTRAR EXPRESSÃO REGULAR', 'gc-label-0083')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_REG', 'Nome', 'gc-label-0084')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_REG', 'Descrição', 'gc-label-0085')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_REG', 'Expressão Regular', 'gc-label-0086')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_REG', 'Tipo de Dado Pessoal', 'gc-label-0087')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_REG', 'Salvar', 'gc-label-0088')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_REG', 'Buscar', 'gc-label-0089')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_REG', 'Cadastro de Script', 'gc-label-0090')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_REG', 'CADASTRAR SCRIPT', 'gc-label-0091')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_REG', 'Nome', 'gc-label-0092')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_REG', 'Descrição', 'gc-label-0093')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_REG', 'Script', 'gc-label-0094')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_REG', 'Tipo de Dado Pessoal', 'gc-label-0095')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_REG', 'Salvar', 'gc-label-0096')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_REG', 'Buscar', 'gc-label-0097')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_REG', 'Cadastro de Finalidade por Base Legal', 'gc-label-0098')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_REG', 'FINALIDADE POR BASE LEGAL', 'gc-label-0099')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_REG', 'Base Legal', 'gc-label-0100')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_REG', 'Finalidade', 'gc-label-0101')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_REG', 'Salvar', 'gc-label-0102')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_REG', 'Buscar', 'gc-label-0103')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Cadastro de Tipo de Dado Pessoal', 'gc-label-0104')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'CADASTRAR TIPO DE DADO PESSOAL', 'gc-label-0105')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Nome', 'gc-label-0106')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Descrição', 'gc-label-0107')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Método de Identificação', 'gc-label-0108')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Expressão Regular', 'gc-label-0109')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Script', 'gc-label-0110')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Inteligência Artificial', 'gc-label-0111')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Categoria de Dado', 'gc-label-0112')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Indireto', 'gc-label-0113')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Direto', 'gc-label-0114')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Sensível', 'gc-label-0115')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Salvar', 'gc-label-0116')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_REG', 'Buscar', 'gc-label-0117')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'Cadastro de Varreduras (DB)', 'gc-label-0118')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'CADASTRAR VARREDURA (DB)', 'gc-label-0119')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'Data', 'gc-label-0120')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'Descrição', 'gc-label-0121')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'Fonte de Dados', 'gc-label-0122')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'Tipo de Varredura', 'gc-label-0123')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'ÚNICA', 'gc-label-0124')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'DIÁRIA', 'gc-label-0125')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'SEMANAL', 'gc-label-0126')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'QUINZENAL', 'gc-label-0127')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'MENSAL', 'gc-label-0128')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'Salvar', 'gc-label-0129')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_DATA_REG', 'Buscar', 'gc-label-0130')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'Cadastro de Varreduras (ARQ)', 'gc-label-0131')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'CADASTRAR VARREDURA (ARQ)', 'gc-label-0132')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'Data', 'gc-label-0133')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'Descrição', 'gc-label-0134')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'Diretório de Arquivos', 'gc-label-0135')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'Tipo de Varredura', 'gc-label-0136')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'ÚNICA', 'gc-label-0137')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'DIÁRIA', 'gc-label-0138')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'SEMANAL', 'gc-label-0139')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'QUINZENAL', 'gc-label-0140')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'MENSAL', 'gc-label-0141')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'Salvar', 'gc-label-0142')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_FILE_REG', 'Buscar', 'gc-label-0143')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('USER_REG', 'Cadastro de Usuário', 'gc-label-0144')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('USER_REG', 'CADASTRAR USUÁRIO', 'gc-label-0145')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('USER_REG', 'Nome', 'gc-label-0146')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('USER_REG', 'E-mail', 'gc-label-0147')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('USER_REG', 'Senha', 'gc-label-0148')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('USER_REG', 'Telefone', 'gc-label-0149')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('USER_REG', 'Perfil de Acesso', 'gc-label-0150')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('USER_REG', 'ADMINISTRADOR', 'gc-label-0151')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('USER_REG', 'AUDITOR', 'gc-label-0152')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('USER_REG', 'Salvar', 'gc-label-0153')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('USER_REG', 'Buscar', 'gc-label-0154')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_REG', 'Atualização de Mensagem de Erro', 'gc-label-0155')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_REG', 'ATUALIZAR MENSAGEM DE ERRO', 'gc-label-0156')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_REG', 'Código', 'gc-label-0157')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_REG', 'Nome', 'gc-label-0158')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_REG', 'Descrição', 'gc-label-0159')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_REG', 'Salvar', 'gc-label-0160')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_REG', 'Buscar', 'gc-label-0161')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_REG', 'Atualização de Mensagens', 'gc-label-0162')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_REG', 'ATUALIZAR MENSAGENS', 'gc-label-0163')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_REG', 'Código', 'gc-label-0164')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_REG', 'Identificador', 'gc-label-0165')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_REG', 'Nome', 'gc-label-0166')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_REG', 'Salvar', 'gc-label-0167')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_REG', 'Buscar', 'gc-label-0168')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('GENERIC_SRC', 'Exportar XLS', 'gc-label-0169')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('GENERIC_SRC', 'Exportar PDF', 'gc-label-0170')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('GENERIC_SRC', 'Cadastrar Novo', 'gc-label-0171')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('GENERIC_SRC', 'Atualizar', 'gc-label-0172')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('GENERIC_SRC', 'Editar', 'gc-label-0173')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('GENERIC_SRC', 'Excluir', 'gc-label-0174')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('GENERIC_SRC', 'Exclusão de Configuração', 'gc-label-0175')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('GENERIC_SRC', 'Não', 'gc-label-0176')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('GENERIC_SRC', 'Sim', 'gc-label-0177')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('GENERIC_SRC', 'Buscar', 'gc-label-0178')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_SRC', 'Pesquisa de Configurações de Aplicativo', 'gc-label-0179')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_SRC', 'CONFIGURAÇÕES DE APLICATIVOS', 'gc-label-0180')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_SRC', 'Nenhuma configuração de aplicativo encontrada.', 'gc-label-0181')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_SRC', 'Nome', 'gc-label-0182')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_SRC', 'Descrição', 'gc-label-0183')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_SRC', 'Parâmetros JVM', 'gc-label-0184')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_SRC', 'Opções', 'gc-label-0185')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuração?', 'gc-label-0186')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('APP_CONFIGURATION_SRC', 'Buscar Configuração de Aplicativo', 'gc-label-0187')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_SRC', 'Pesquisa de Tipos de Fontes de Dados', 'gc-label-0188')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_SRC', 'TIPOS DE FONTES DE DADOS', 'gc-label-0189')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_SRC', 'Nenhum Tipo de Base de Dados foi encontrado.', 'gc-label-0190')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_SRC', 'Nome', 'gc-label-0191')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_SRC', 'Descrição', 'gc-label-0192')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_SRC', 'Driver', 'gc-label-0193')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_SRC', 'Prefixo', 'gc-label-0194')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_SRC', 'Opções', 'gc-label-0195')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuração?', 'gc-label-0196')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATABASE_TYPE_SRC', 'Buscar Tipo de Base de Dados', 'gc-label-0197')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_SRC', 'Pesquisa de Fontes de Dados', 'gc-label-0198')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_SRC', 'FONTES DE DADOS', 'gc-label-0199')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_SRC', 'Nenhuma fonte de dados foi encontrada.', 'gc-label-0200')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_SRC', 'Nome', 'gc-label-0201')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_SRC', 'Descrição', 'gc-label-0202')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_SRC', 'Url', 'gc-label-0203')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_SRC', 'Finalidade por Base Legal', 'gc-label-0204')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_SRC', 'Aprendizado', 'gc-label-0205')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_SRC', 'Opções', 'gc-label-0206')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuração?', 'gc-label-0207')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('DATASOURCE_SRC', 'Buscar Fonte de Dados', 'gc-label-0208')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_SRC', 'Pesquisa de Mensagens de Erro', 'gc-label-0209')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_SRC', 'MENSAGENS DE ERRO', 'gc-label-0210')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_SRC', 'Nenhuma mensagem de erro foi encontrada.', 'gc-label-0211')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_SRC', 'Código', 'gc-label-0212')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_SRC', 'Nome', 'gc-label-0213')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_SRC', 'Descrição', 'gc-label-0214')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_SRC', 'Opções', 'gc-label-0215')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('ERROR_MESSAGE_SRC', 'Buscar Mensagem de Erro', 'gc-label-0216')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_SRC', 'Pesquisa de Diretórios', 'gc-label-0217')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_SRC', 'DIRETÓRIOS', 'gc-label-0218')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_SRC', 'Nenhuma fonte de dados foi encontrada.', 'gc-label-0219')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_SRC', 'Nome', 'gc-label-0220')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_SRC', 'Descrição', 'gc-label-0221')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_SRC', 'Diretório', 'gc-label-0222')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_SRC', 'Finalidade por Base Legal', 'gc-label-0223')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_SRC', 'Opções', 'gc-label-0224')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuração?', 'gc-label-0225')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FILESOURCE_SRC', 'Buscar Fonte de Dados', 'gc-label-0226')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_SRC', 'Pesquisa de Finalidades', 'gc-label-0227')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_SRC', 'FINALIDADES', 'gc-label-0228')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_SRC', 'Nenhuma finalidade foi encontrada.', 'gc-label-0229')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_SRC', 'Nome', 'gc-label-0230')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_SRC', 'Descrição', 'gc-label-0231')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_SRC', 'Opções', 'gc-label-0232')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuração?', 'gc-label-0233')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('FINALITY_SRC', 'Buscar Finalidade', 'gc-label-0234')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_SRC', 'Pesquisa de Colunas de Identificação', 'gc-label-0235')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_SRC', 'COLUNAS DE IDENTIFICAÇÃO', 'gc-label-0236')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_SRC', 'Nenhuma Coluna de Identificação foi encontrada.', 'gc-label-0237')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_SRC', 'Nome', 'gc-label-0238')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_SRC', 'Opções', 'gc-label-0239')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuração?', 'gc-label-0240')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_COLUMN_SRC', 'Buscar Coluna de Identificação', 'gc-label-0241')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_SRC', 'Pesquisa de Campos de Identificação', 'gc-label-0242')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_SRC', 'CAMPOS DE IDENTIFICAÇÃO', 'gc-label-0243')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_SRC', 'Nenhum Campo de Identificação foi encontrado.', 'gc-label-0244')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_SRC', 'Nome', 'gc-label-0245')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_SRC', 'Tipo de Dado Pessoal', 'gc-label-0246')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_SRC', 'Método de Identificação', 'gc-label-0247')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_SRC', 'Colunas de Identificação', 'gc-label-0248')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_SRC', 'Opções', 'gc-label-0249')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuração?', 'gc-label-0250')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('IDENTIFICATION_FIELD_SRC', 'Buscar Campo de Identificação', 'gc-label-0251')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_SRC', 'Pesquisa de Mensagens', 'gc-label-0252')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_SRC', 'MENSAGENS', 'gc-label-0253')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_SRC', 'Nenhuma mensagem foi encontrada.', 'gc-label-0254')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_SRC', 'Código', 'gc-label-0255')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_SRC', 'Identificador de Página', 'gc-label-0256')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_SRC', 'Descrição', 'gc-label-0257')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_SRC', 'Opções', 'gc-label-0258')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('JSF_LABEL_SRC', 'Buscar Mensagem', 'gc-label-0259')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'Pesquisa de Data', 'gc-label-0260')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'DATA', 'gc-label-0261')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'Nenhuma Aprendizagem de Dados foi encontrada.', 'gc-label-0262')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'Nome', 'gc-label-0263')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'Descrição', 'gc-label-0264')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'Tabela de Treino', 'gc-label-0265')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'Coluna de Decisão', 'gc-label-0266')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'Coluna de Classe', 'gc-label-0267')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'Fonte de Treino', 'gc-label-0268')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'Opções', 'gc-label-0269')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuração?', 'gc-label-0270')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_DATA_SRC', 'Buscar Aprendizagem de Dados', 'gc-label-0271')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_SRC', 'Pesquisa de Expressões Regulares', 'gc-label-0272')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_SRC', 'EXPRESSÕES REGULARES', 'gc-label-0273')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_SRC', 'Nenhuma Expressão Regular foi encontrada.', 'gc-label-0274')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_SRC', 'Nome', 'gc-label-0275')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_SRC', 'Descrição', 'gc-label-0276')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_SRC', 'Expressão Regular', 'gc-label-0277')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_SRC', 'Tipo de Dado Pessoal', 'gc-label-0278')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_SRC', 'Opções', 'gc-label-0279')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuração?', 'gc-label-0280')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_REGEX_SRC', 'Buscar Expressão Regular', 'gc-label-0281')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_SRC', 'Pesquisa de Scripts', 'gc-label-0282')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_SRC', 'SCRIPTS', 'gc-label-0283')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_SRC', 'Nenhum Script foi encontrado.', 'gc-label-0284')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_SRC', 'Nome', 'gc-label-0285')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_SRC', 'Descrição', 'gc-label-0286')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_SRC', 'Script', 'gc-label-0287')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_SRC', 'Tipo de Dado Pessoal', 'gc-label-0288')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_SRC', 'Opções', 'gc-label-0289')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuração?', 'gc-label-0290')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEARNING_SCRIPT_SRC', 'Buscar Script', 'gc-label-0291')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_SRC', 'Pesquisa de Finalidades por Base Legal', 'gc-label-0292')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_SRC', 'FINALIDADES POR BASE LEGAL', 'gc-label-0293')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_SRC', 'Nenhuma Finalidade por Base Legal foi encontrada.', 'gc-label-0294')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_SRC', 'Base Legal', 'gc-label-0295')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_SRC', 'Finalidades', 'gc-label-0296')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_SRC', 'Opções', 'gc-label-0297')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuração?', 'gc-label-0298')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_FINALITY_SRC', 'Buscar Finalidade por Base Legal', 'gc-label-0299')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_SRC', 'Pesquisa de Bases Legais', 'gc-label-0300')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_SRC', 'BASES LEGAIS', 'gc-label-0301')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_SRC', 'Nenhuma Base Legal foi encontrada.', 'gc-label-0302')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_SRC', 'Nome', 'gc-label-0303')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_SRC', 'Descrição', 'gc-label-0304')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('LEGAL_BASE_SRC', 'Buscar Base Legal', 'gc-label-0305')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_SRC', 'Pesquisa de Tipos de Dados Pessoais', 'gc-label-0306')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_SRC', 'TIPOS DE DADOS PESSOAIS', 'gc-label-0307')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_SRC', 'Nenhum tipo de dado pessoal encontrado foi encontrado.', 'gc-label-0308')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_SRC', 'Nome', 'gc-label-0309')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_SRC', 'Descrição', 'gc-label-0310')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_SRC', 'Método de Identificação', 'gc-label-0311')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_SRC', 'Categoria de Dado', 'gc-label-0312')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_SRC', 'Opções', 'gc-label-0313')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuraão?', 'gc-label-0314')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('PERSONAL_DATA_TYPE_SRC', 'Buscar Tipo de Dado Pessoal', 'gc-label-0315')

INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'Pesquisa de Agendamentos', 'gc-label-0316')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'AGENDAMENTOS', 'gc-label-0317')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'Nenhum agendamento encontrado.', 'gc-label-0318')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'Data', 'gc-label-0319')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'Nome', 'gc-label-0320')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'Tipo', 'gc-label-0321')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'Status', 'gc-label-0322')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'Opções', 'gc-label-0323')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'Tem certeza de que deseja realizar a exclusão desta configuraão?', 'gc-label-0324')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'Buscar Agendamento', 'gc-label-0325')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'Escolha:', 'gc-label-0326')
INSERT INTO jsf_label (jsf_bean, label, jsf_code) VALUES ('SCAN_SCHEDULE_SRC', 'Você pode escolher se deseja adicionar uma fonte de dados do tipo Banco de Dados ou Arquivo', 'gc-label-0327')





IF EXISTS(SELECT 'vw_other_correlation_fields' FROM INFORMATION_SCHEMA.VIEWS) BEGIN DROP VIEW vw_other_correlation_fields END
CREATE VIEW vw_other_correlation_fields AS SELECT id, datasource_name, table_name, column_name, (SELECT top 1 column_name FROM personal_data_locations WHERE id_personal_data_type = (SELECT top 1 id FROM personal_data_types WHERE name like 'CPF'))first_factor, (SELECT top 1 column_name FROM personal_data_locations WHERE id_personal_data_type = (SELECT top 1 id FROM personal_data_types WHERE name like 'RG'))second_factor, (SELECT top 1 column_name FROM personal_data_locations WHERE id_personal_data_type = (SELECT top 1 id FROM personal_data_types WHERE name like 'NOME'))third_factor FROM personal_data_locations WHERE id_personal_data_type not in (SELECT id FROM personal_data_types WHERE name in  ('NOME', 'CPF', 'RG'))